package gameModel.entity;

public enum VisType {
	INVENTORY,INVENTORY_ARROW,INVENTORY_BOMB,INVENTORY_TREASURE,INVENTORY_SWORD, INVENTORY_KEY,ARROW, PLAYER, HUNTER, SWORD, TREASURE, EXIT, PIT, HOVER_POTION, INVINCIBILITY_POTION, EMPTY_TILE, SWITCH, BOULDER, BOMB, KEY, DOOR, WALL, HOUND, COWARD, STRATEGIST, LIT_BOMB
}
